resolver: https://raw.githubusercontent.com/nikita-volkov/stack-snapshot/bb436b1b88ef65e7e5bba67e7950a0ecb7488a7e/snapshot.yaml
extra-deps:
- git: https://github.com/nikita-volkov/ptr-poker
  commit: 5521535686b77fe540328857beeeeb22843e7b61
