resolver: https://raw.githubusercontent.com/nikita-volkov/stack-snapshot/863fba363a57fe254f0556d102dfd13e42259c26/snapshot.yaml
extra-deps:
- git: https://github.com/nikita-volkov/ptr-poker
  commit: b525f9b8041f4392157f7c77585cd253e04e5d2f
